version: 2.0
jobs:
  build:
    docker:
      - image: node:17.9.0-alpine
    steps:
      - checkout
      - run: |
          # build client
          yarn install && yarn build

          # TODO: add options for dev and prod

          # deploy client
          yarn global add firebase-tools && firebase deploy --only hosting --token "1//0gFTRgmn-UCniCgYIARAAGBASNwF-L9Ir5ckzYoWpB27XSapaYv_0zHKMxktghElLmivieQ17EsNPI8_E6S0tGU3gQ5__XXvdHP4"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
